### ISSUE TITLE
Runtime error with cv_bridge_boost

### ISSUE THREAD

**Issue by camcrt** [tentone/tello-ros2#3]
Hello, 

I am trying to use your ROS2 Tello node on Foxy, Ubuntu 20.04 but I always get an error about cv_bridge_boost. The Tello node crashes at startup. 

Please find the trace: 
```
[INFO] [launch]: All log files can be found below /home/camille/.ros/log/2022-04-12-16-00-37-900309-PC-Drone-Swarming-39164
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [tello-1]: process started with pid [39166]
[INFO] [tello_control-2]: process started with pid [39168]
[INFO] [static_transform_publisher-3]: process started with pid [39170]
[static_transform_publisher-3] [INFO] [1649772037.967412362] [tf]: Spinning until killed publishing transform from 'map' to 'drone'
[tello-1] RuntimeError: FATAL: module compiled as little endian, but detected different endianness at runtime
[tello-1] Traceback (most recent call last):
[tello-1]   File "/home/camille/Documents/ros2_swarm/tello-ros2/workspace/install/tello/lib/tello/tello", line 11, in <module>
[tello-1]     load_entry_point('tello', 'console_scripts', 'tello')()
[tello-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
[tello-1]     return get_distribution(dist).load_entry_point(group, name)
[tello-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
[tello-1]     return ep.load()
[tello-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
[tello-1]     return self.resolve()
[tello-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
[tello-1]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
[tello-1]   File "/home/camille/Documents/ros2_swarm/tello-ros2/workspace/build/tello/tello/node.py", line 23, in <module>
[tello-1]     from cv_bridge import CvBridge
[tello-1]   File "/usr/lib/python3/dist-packages/cv_bridge/__init__.py", line 6, in <module>
[tello-1]     from cv_bridge.boost.cv_bridge_boost import cvtColorForDisplay, getCvType
[tello-1] SystemError: initialization of cv_bridge_boost raised unreported exception
[ERROR] [tello-1]: process has died [pid 39166, exit code 1, cmd '/home/camille/Documents/ros2_swarm/tello-ros2/workspace/install/tello/lib/tello/tello --ros-args -r __node:=tello -r __ns:=/ --params-file /tmp/launch_params_s36z8217 --params-file /tmp/launch_params_6yadarlc --params-file /tmp/launch_params_bdzwut2j --params-file /tmp/launch_params_y_elw_8y -r /image_raw:=/camera'].
[INFO] [tello-1]: process started with pid [39207]
[tello-1] RuntimeError: FATAL: module compiled as little endian, but detected different endianness at runtime
[tello-1] Traceback (most recent call last):
[tello-1]   File "/home/camille/Documents/ros2_swarm/tello-ros2/workspace/install/tello/lib/tello/tello", line 11, in <module>
[tello-1]     load_entry_point('tello', 'console_scripts', 'tello')()
[tello-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
[tello-1]     return get_distribution(dist).load_entry_point(group, name)
[tello-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
[tello-1]     return ep.load()
[tello-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
[tello-1]     return self.resolve()
[tello-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
[tello-1]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
[tello-1]   File "/home/camille/Documents/ros2_swarm/tello-ros2/workspace/build/tello/tello/node.py", line 23, in <module>
[tello-1]     from cv_bridge import CvBridge
[tello-1]   File "/usr/lib/python3/dist-packages/cv_bridge/__init__.py", line 6, in <module>
[tello-1]     from cv_bridge.boost.cv_bridge_boost import cvtColorForDisplay, getCvType
[tello-1] SystemError: initialization of cv_bridge_boost raised unreported exception
[ERROR] [tello-1]: process has died [pid 39207, exit code 1, cmd '/home/camille/Documents/ros2_swarm/tello-ros2/workspace/install/tello/lib/tello/tello --ros-args -r __node:=tello -r __ns:=/ --params-file /tmp/launch_params_s36z8217 --params-file /tmp/launch_params_6yadarlc --params-file /tmp/launch_params_bdzwut2j --params-file /tmp/launch_params_y_elw_8y -r /image_raw:=/camera'].
```

I don't understand this line as I used packages from the Ubuntu OS : 
RuntimeError: FATAL: module compiled as little endian, but detected different endianness at runtime

Do you have an idea how to solve it? 

Thanks a lot.

**Comment by tentone** [comment]
Hello

In wich computer/CPU was this compiled on?

Thanks a lot!

**Comment by gdherbom** [comment]
Hello @tentone, 

Thanks for your reply we are working on DELL workstation with Intel processor. 
Is your code specific to ARM platform? 
Regards,

Gerald

**Comment by tentone** [comment]
This should work correctly both on ARM and Intel/AMD based CPU.

Seems to be an issue related with the boost lib. Possibly can be solved by using an older version of the opencv-bridge dependency. I have to check

https://github.com/ros-perception/vision_opencv/pull/292

**Comment by gdherbom** [comment]
Hello @tentone 
After reinstalling all the tool-chain (Ubuntu, ROS2, our application and your package), the problem disappeared. Seems to be a problem of installation. 
I think you can close the issue. 
We will try the swarm now. 
Thanks for the availability of this package. 
Gerald

**Comment by tentone** [comment]
Thanks a lot. Glad that you were able to solve the problem with a clean install.

Cheers!
